"""add ticket resolved periods

Revision ID: 0195f8a5916d
Revises: f4356d248630
Create Date: 2026-08-29 18:45:09.886272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.database


# revision identifiers, used by Alembic.
revision: str = '0195f8a5916d'
down_revision: Union[str, None] = 'f4356d248630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_resolved_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_resolved_periods_ticket_id'), 'ticket_resolved_periods', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_resolved_periods_ticket_id'), table_name='ticket_resolved_periods')
    op.drop_table('ticket_resolved_periods')
    # ### end Alembic commands ###
