"""add ticket resolved_at

Revision ID: 1ee76b75cd49
Revises: 796b56918243
Create Date: 2026-08-29 17:57:43.730814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.database


# revision identifiers, used by Alembic.
revision: str = '1ee76b75cd49'
down_revision: Union[str, None] = '796b56918243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('resolved_at', app.core.database.UTCDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'resolved_at')
    # ### end Alembic commands ###
