"""add ticket lifecycle period tables

Revision ID: 324d9e38d957
Revises: 1b04066827ff
Create Date: 2026-08-29 13:00:52.952527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.database


# revision identifiers, used by Alembic.
revision: str = '324d9e38d957'
down_revision: Union[str, None] = '1b04066827ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_closed_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('closed_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reopened_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_closed_periods_ticket_id'), 'ticket_closed_periods', ['ticket_id'], unique=False)
    op.create_table('ticket_pending_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_pending_periods_ticket_id'), 'ticket_pending_periods', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_pending_periods_ticket_id'), table_name='ticket_pending_periods')
    op.drop_table('ticket_pending_periods')
    op.drop_index(op.f('ix_ticket_closed_periods_ticket_id'), table_name='ticket_closed_periods')
    op.drop_table('ticket_closed_periods')
    # ### end Alembic commands ###
