"""add ticket history events

Revision ID: 98a3fcb7c23d
Revises: 1ee76b75cd49
Create Date: 2026-08-29 18:15:38.342120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.database


# revision identifiers, used by Alembic.
revision: str = '98a3fcb7c23d'
down_revision: Union[str, None] = '1ee76b75cd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_history_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('status_change', 'reassignment', 'reply', name='tickethistoryeventtype', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('old_status', sa.Enum('new', 'open', 'pending', 'resolved', 'closed', name='ticketstatus', native_enum=False, length=20), nullable=True),
    sa.Column('new_status', sa.Enum('new', 'open', 'pending', 'resolved', 'closed', name='ticketstatus', native_enum=False, length=20), nullable=True),
    sa.Column('old_assignee_id', sa.Integer(), nullable=True),
    sa.Column('new_assignee_id', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['old_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_history_events_ticket_id'), 'ticket_history_events', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_history_events_ticket_id'), table_name='ticket_history_events')
    op.drop_table('ticket_history_events')
    # ### end Alembic commands ###
