"""add sla acknowledgements

Revision ID: f4356d248630
Revises: 98a3fcb7c23d
Create Date: 2026-08-29 18:33:02.107565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.database


# revision identifiers, used by Alembic.
revision: str = 'f4356d248630'
down_revision: Union[str, None] = '98a3fcb7c23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('breach_epoch', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'user_id', 'breach_epoch', name='uq_sla_ack_ticket_user_epoch')
    )
    op.create_index(op.f('ix_sla_acknowledgements_ticket_id'), 'sla_acknowledgements', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_sla_acknowledgements_user_id'), 'sla_acknowledgements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_acknowledgements_user_id'), table_name='sla_acknowledgements')
    op.drop_index(op.f('ix_sla_acknowledgements_ticket_id'), table_name='sla_acknowledgements')
    op.drop_table('sla_acknowledgements')
    # ### end Alembic commands ###
