"""add tickets table

Revision ID: ff47661fc0f9
Revises: ebfc6b286261
Create Date: 2026-08-29 12:39:51.051125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff47661fc0f9'
down_revision: Union[str, None] = 'ebfc6b286261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requester', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='ticketpriority', native_enum=False, length=20), nullable=False),
    sa.Column('category', sa.Enum('bug', 'billing', 'how_to', 'feature_request', 'other', name='ticketcategory', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('new', 'open', 'pending', 'resolved', 'closed', name='ticketstatus', native_enum=False, length=20), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
